apiVersion: v1
kind: ConfigMap
metadata:
  name: agripulse-config
  namespace: agripulse
data:
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://mseureka:4040/eureka/"
  SPRING_CONFIG_IMPORT: "optional:configserver:http://configserver:9999"
  SPRING_CLOUD_CONFIG_URI: "http://configserver:9999"
  SPRING_CLOUD_CONFIG_ENABLED: "true"
  SPRING_CLOUD_CONFIG_FAIL_FAST: "false"
  DB_HOST: "mysql"
  DB_PORT: "3306"
  KAFKA_HOST: "kafka"
  KAFKA_PORT: "9092"
