apiVersion: apps/v1
kind: Deployment
metadata:
  name: mseureka
  namespace: agripulse
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mseureka
  template:
    metadata:
      labels:
        app: mseureka
    spec:
      containers:
      - name: mseureka
        image: agripulse/mseureka:1.0
        ports:
        - containerPort: 4040
---
apiVersion: v1
kind: Service
metadata:
  name: mseureka
  namespace: agripulse
spec:
  type: ClusterIP
  selector:
    app: mseureka
  ports:
  - port: 4040
    targetPort: 4040
