spring.application.name=MSNotification
server.port=9097

# IMPORTANT
spring.config.import=optional:configserver:http://configserver:9999

eureka.client.registerWithEureka=true
eureka.client.fetchRegistry=true
eureka.client.serviceUrl.defaultZone=http://${EUREKA_HOST:localhost}:${EUREKA_PORT:4040}/eureka
